[package]
name = "bitbank"
version = "0.1.0"
authors = ["yamazakidaisuke"]

[dependencies]
reqwest="0.6.2"
serde="1.0.8"
serde_json="1.0.2"
time="0.1.37"
rust-crypto="0.2.36"
rustc-serialize="0.3.24"
hyper="0.10.10"
url="1.4.0"
